name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt-get install xorg-dev
    - name: build dir and cmake
      run: mkdir build && cd build && cmake ..
    - name: run build
      run: cd build && make
